// <auto-generated />
using System;
using Locatic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locatic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625182541_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Locatic.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            EndDate = new DateOnly(2024, 7, 7),
                            StartDate = new DateOnly(2024, 7, 1)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 3,
                            ClientId = 2,
                            EndDate = new DateOnly(2024, 8, 20),
                            StartDate = new DateOnly(2024, 8, 15)
                        });
                });

            modelBuilder.Entity("Locatic.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DayRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fuel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            DayRate = 35m,
                            Fuel = 1,
                            NbSeats = 5,
                            Registration = "AB-123-CD",
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 2,
                            DayRate = 45m,
                            Fuel = 0,
                            NbSeats = 5,
                            Registration = "EF-456-GH",
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 3,
                            DayRate = 40m,
                            Fuel = 2,
                            NbSeats = 5,
                            Registration = "IJ-789-KL",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 4,
                            DayRate = 50m,
                            Fuel = 0,
                            NbSeats = 5,
                            Registration = "MN-012-OP",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("Locatic.Models.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "France",
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "France",
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "Allemagne",
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Locatic.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarBrandId = 1,
                            Name = "Clio"
                        },
                        new
                        {
                            Id = 2,
                            CarBrandId = 1,
                            Name = "Megane"
                        },
                        new
                        {
                            Id = 3,
                            CarBrandId = 2,
                            Name = "208"
                        },
                        new
                        {
                            Id = 4,
                            CarBrandId = 3,
                            Name = "Golf"
                        });
                });

            modelBuilder.Entity("Locatic.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sophie.martin@email.com",
                            FirstName = "Sophie",
                            LastName = "Martin",
                            PhoneNumber = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "pierre.dupont@email.com",
                            FirstName = "Pierre",
                            LastName = "Dupont",
                            PhoneNumber = "0698765432"
                        });
                });

            modelBuilder.Entity("Locatic.Models.Booking", b =>
                {
                    b.HasOne("Locatic.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locatic.Models.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Locatic.Models.Car", b =>
                {
                    b.HasOne("Locatic.Models.CarModel", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Locatic.Models.CarModel", b =>
                {
                    b.HasOne("Locatic.Models.CarBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Locatic.Models.CarBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Locatic.Models.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Locatic.Models.Client", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
